### ISSUE TITLE
Add auto sizing for shortcuts

### ISSUE THREAD

**Issue by nodthenbow** [enfyna/fx-new-tab#1]
Add in a setting that sizes the clickable area of the shortcuts to auto fill the whole window (or the whole portion of the window allocated to that div). Ideally I would like to set the number of rows and columns and then it fits it into the shortcut area without scrolling

This would fix the problem where having a full screen layout and a vertical half screen layout in use for the same browser only one of them will be properly sized.

Ideally if I had a 102 by 102px window size, the whole thing was used for shortcuts, and I have it set to 5 columns with 3 full rows worth of items the clickable area of each shortcut should be 20 by 34px (minus a 3px ish padding)

The hacky way to do this is to change the bootstrap css and change .card to have height:(100/rows - 5ish)vh and also add access to the .m-auto setting which already has the class implemented. Ideally you'd set the thumbnail to shrink/grow to the height of the clickable area, which this doesn't, but I'm assuming you know a better way to implement this anyways.

**Comment by enfyna** [comment]
Hi! This is my first ever issue on my own project so I am very excited! And I would like to implement the feature you want. :)

But I didnt understand some things. So do you want to instead of setting shortcut columns % value (like %25, %20, %12.5 ...) to be like a row and column selection (like 3x5, 3x6, 4x5 ...) ? And if you want to be it like this what should happen for example if the user selected the 3x5 option and wanted to add a 16th shortcut ? 

> This would fix the problem where having a full screen layout and a vertical half screen layout in use for the same browser only one of them will be properly sized.

Well I guess you are right here because the full screen and the half screen layout looks pretty different but I think that people generally use the browser full screen and if they have something to do they split the screen in half. Because of this I put the shortcuts on top so they are easier to click. And I cant think of anywhere else to put them. Can you maybe add some screenshots or a simple drawing that shows how it looks now and how you wanted it to look ?

Thanks!

**Comment by nodthenbow** [comment]
> But I didnt understand some things. So do you want to instead of setting shortcut columns % value (like %25, %20, %12.5 ...) to be like a row and column selection (like 3x5, 3x6, 4x5 ...) ? And if you want to be it like this what should happen for example if the user selected the 3x5 option and wanted to add a 16th shortcut ?

Essentially I'm asking for an option to set it so it will have X columns, then it figures out how many rows that is, and then sizes the height of the clickable area of the rows so that it fills as much of the screen as possible without needing to scroll (and also the other way around, set rows, it figures out number of columns). 

This is what it currently looks like (if you size it for half width or a rotated layout)
![image](https://github.com/enfyna/fx-new-tab/assets/12620288/7d61f957-57b8-4473-972f-5796643f25e6)
(If you size it for a full screen layout the shortcuts will be very small on the half screen layout)

This is what I would like it to look like (if the user selected either 4 columns or 3 rows)
![image](https://github.com/enfyna/fx-new-tab/assets/12620288/e4375101-8192-4c02-9bef-e2012caf9296)

Ideally only the clickable area gets stretched, not the image or text inside it.

**Comment by enfyna** [comment]
Hi! I am sorry for the late response. 
I changed how the shortcuts align and made it a bit more consistent on how they look on  fullscreen and half screen. You can test it in the new release (1.13.0).
I looked into this and added autoshort. It is way simpler than this but it gets the job done I guess. Set the container width to 100% and enable autoshort. If the shortcuts overflow it will narrow the container to fit the screen. Sadly I couldnt come up with an idea to stretch it to full screen. And I think it would have taken me too much time. 
Anyway I am going to close this issue for now but if you still have an issue we can open it again.
