### ISSUE TITLE
Minimum Icon Size Limit

### ISSUE THREAD

**Issue by Dirge70** [enfyna/fx-new-tab#3]
**Is your feature request related to a problem? Please describe.**
When the browser window is narrow, the icons are scaled so small it's hard to see. 

**Describe the solution you'd like**
Set a limit to how small the icons can get.

**Describe alternatives you've considered**
Tried to make the icons bigger, but since it's a %, when the browser window is larger, the icons are huge.

![min_icon_size](https://github.com/enfyna/fx-new-tab/assets/104225510/5bea59be-0a5a-4d94-9d33-b7ca61f87ce3)

**Comment by enfyna** [comment]
Hi! So I tried to do this but because of the min width property sometimes the shortcuts can wrap. 


https://github.com/enfyna/fx-new-tab/assets/91965312/822402c8-1647-4de2-9696-bc2c2a83fc7b


In the first part of the video shortcuts have no min width so they dont wrap but in the second part i set min width to 64 px and because of this 2 shortcuts wrap around. 

Well I think this should be expected behaviour because how else could all the shortcuts fit I guess.

**Comment by Dirge70** [comment]
I think that is a great solution. Either they wrap or get cut off. Thank you for looking into this!

**Comment by enfyna** [comment]
Added in 1.13.1
